title: Wang Yaoyang's Homepage
page-top-title: Wang Yaoyang
top-section-bg-text: Intelligent Transportation Systems
home-subtitle: Wang Yaoyang&ensp;|&ensp;王耀阳
# copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
